const {chromium}=require('C:/Users/KUNAL/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
(async()=>{
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1040},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4191/Little-Legacy-Prototype.html');await page.waitForTimeout(500);
if(errors.length)throw new Error(errors.join('\n'));
const ids=await page.evaluate(()=>LL.screens.map(s=>s.id));const report={screenCount:ids.length,layouts:[],errors};
for(const id of ids){await page.evaluate(id=>LL.render(id,{initial:true}),id);await page.waitForTimeout(30);const result=await page.evaluate(()=>{const screen=document.querySelector('.screen:last-of-type');const scroll=screen.querySelector('.scroll');return {id:LL.st.id,horizontalOverflow:scroll.scrollWidth>scroll.clientWidth+2,heading:screen.querySelector('h1').textContent,buttons:[...screen.querySelectorAll('button')].filter(b=>b.getBoundingClientRect().height<44).map(b=>b.textContent)}});report.layouts.push(result);}
await page.evaluate(()=>LL.render('home',{initial:true}));await page.waitForTimeout(450);await page.screenshot({path:__dirname+'/preview-home.png',fullPage:true});
await page.locator('.screen:last-of-type [data-go="children"]').click();await page.waitForTimeout(400);report.sheet=await page.locator('[role=dialog]').count()===1;await page.locator('[role=dialog]').getByRole('button',{name:/Leo/}).click();await page.waitForTimeout(420);report.childSwitch=await page.evaluate(()=>LL.st.child==='Leo');
await page.evaluate(()=>LL.render('appearance',{initial:true}));await page.locator('.screen:last-of-type [data-theme="Dark"]').click();await page.waitForTimeout(350);report.dark=await page.evaluate(()=>getComputedStyle(document.querySelector('#device')).getPropertyValue('--bg').trim()==='#1D1926');await page.screenshot({path:__dirname+'/preview-dark.png',fullPage:true});
await page.locator('.screen:last-of-type [data-theme="System"]').click();await page.emulateMedia({colorScheme:'light'});await page.waitForTimeout(300);report.systemLight=await page.evaluate(()=>getComputedStyle(document.querySelector('#device')).getPropertyValue('--bg').trim()==='#FAF8F4');await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.waitForTimeout(300);report.systemDark=await page.evaluate(()=>getComputedStyle(document.querySelector('#device')).getPropertyValue('--bg').trim()==='#1D1926');report.reducedMotion=await page.locator('#device.reduced').count()===1;
await page.emulateMedia({colorScheme:'light',reducedMotion:'no-preference'});await page.evaluate(()=>{LL.st.theme='Light';LL.st.child='Maya';LL.render('signin',{initial:true})});await page.locator('.screen:last-of-type .primary').click();report.formError=await page.locator('.error').count()===1;await page.locator('#signin-0').fill('demo@example.com');await page.locator('#signin-1').fill('sample-password');await page.locator('.screen:last-of-type .primary').click();await page.waitForTimeout(800);report.signin=await page.evaluate(()=>LL.st.id==='home');
await page.evaluate(()=>LL.render('celebration',{initial:true}));await page.locator('.screen:last-of-type').getByRole('button',{name:'Skip celebration',exact:true}).click();await page.waitForTimeout(400);report.skipCelebration=await page.evaluate(()=>LL.st.id==='progress');await page.screenshot({path:__dirname+'/preview-progress.png',fullPage:true});
await page.evaluate(()=>LL.render('home',{initial:true}));await page.locator('#tablet').click();await page.setViewportSize({width:1280,height:1200});await page.waitForTimeout(300);await page.screenshot({path:__dirname+'/preview-tablet.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.querySelector('#device').classList.remove('tablet');document.body.classList.remove('tablet-mode');LL.render('home',{initial:true})});await page.waitForTimeout(400);await page.screenshot({path:__dirname+'/preview-mobile.png'});report.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
report.links=await page.evaluate(()=>LL.screens.flatMap(s=>[...s.items.filter(i=>i.to).map(i=>i.to),...s.actions.map(a=>a.to)]).filter(id=>!id.startsWith('@')&&!LL.screens.some(s=>s.id===id)));
fs.writeFileSync(__dirname+'/validation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
