from pathlib import Path
p=Path(__file__).with_name('prototype-template.html');s=p.read_text(encoding='utf-8')
def rep(a,b):
    global s
    assert a in s,a[:100]
    s=s.replace(a,b)
rep('const screens=__SCREEN_DATA__,arts=__ART_DATA__,themes=__THEME_DATA__;','const screens=__SCREEN_DATA__,arts=__ART_DATA__,themes=__THEME_DATA__,books=__BOOK_DATA__;const booksById=Object.fromEntries(books.map(b=>[b.id,b]));')
rep("sheet:false};","sheet:false,storyCategory:'All'};")
css='''<style>
.story-categories{margin:0 0 8px}.category-label{font-size:14px;margin:0 0 12px;font-weight:700}.category-chips{display:flex;flex-wrap:wrap;gap:8px}.category-chip{border:1px solid var(--border);background:var(--card);color:var(--muted);min-height:44px;padding:10px 16px;border-radius:30px;font-size:13px}.category-chip[aria-pressed=true]{background:var(--primary);color:var(--onPrimary);border-color:transparent;font-weight:700}.shelf-heading{display:flex;align-items:center;justify-content:space-between;margin:6px 0 18px}.shelf-heading h2{font-size:20px;letter-spacing:-.6px;margin:0}.shelf-heading span{font-size:12px;color:var(--muted)}.book-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px 16px}.book-tile{display:flex;flex-direction:column;gap:12px;min-width:0;text-align:left;border:0;padding:0;background:transparent;color:var(--text);border-radius:12px}.book-tile[hidden]{display:none}.book-cover{display:block;width:100%;aspect-ratio:3/4;border-radius:11px;overflow:hidden;box-shadow:0 8px 15px #2516310c}.book-cover svg{display:block;width:100%;height:100%}.book-title{font-size:15px;font-weight:700;line-height:1.5;letter-spacing:-.3px;padding:0 1px}.book-detail .topbar{margin-bottom:16px}.book-detail-cover{width:180px;margin:0 auto 26px;box-shadow:0 16px 26px #25163114}.book-summary h1{font-size:26px;line-height:1.3;letter-spacing:-.8px;margin:0 0 10px;outline:none}.book-meta{display:flex;align-items:center;gap:8px;color:var(--primary);font-size:12px;font-weight:650;margin:0 0 15px}.book-meta span:first-child{background:var(--soft);padding:7px 12px;border-radius:20px}.book-description{font-size:15px;line-height:1.8;color:var(--muted);margin:0}.chapters-section{margin-top:12px}.chapters-heading{font-size:20px;letter-spacing:-.5px;margin:0 0 14px}.chapter-list{display:flex;flex-direction:column;gap:10px}.chapter-row{display:flex;align-items:center;gap:14px;background:var(--card);color:var(--text);border:1px solid var(--border);border-radius:16px;text-align:left;width:100%;min-height:64px;padding:12px 15px}.chapter-number{display:flex;align-items:center;justify-content:center;width:34px;height:34px;flex-shrink:0;background:var(--soft);border-radius:10px;color:var(--primary);font-size:12px;font-weight:700}.chapter-name{font-size:14px;font-weight:600;line-height:1.5}.chapter-row .chev{margin-left:auto;color:var(--muted)}.chapter-art{padding:16px;height:280px!important}.chapter-art svg{width:180px;max-height:100%;border-radius:10px}.device[data-palette=Wireframe] .book-cover,.device[data-palette=Wireframe] .chapter-art svg{filter:grayscale(1)}.tablet .book-grid{grid-template-columns:repeat(3,minmax(0,1fr));gap:28px 20px}.tablet .book-detail-cover{width:220px}.tablet .book-summary{max-width:560px;margin:auto}.library .page-heading{padding-bottom:20px}@media(max-width:740px){.tablet .book-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.tablet .book-detail-cover{width:180px}}
</style>'''
rep('</head>',css+'</head>')
branches='''if(type==='story-categories')return `<section class="story-categories" aria-label="Story categories"><h2 class="category-label">Categories</h2><div class="category-chips">${it.categories.map(c=>`<button class="category-chip" data-category="${esc(c)}" aria-pressed="${st.storyCategory===c}">${st.storyCategory===c?'✓ ':''}${esc(c)}</button>`).join('')}</div></section>`;
if(type==='book-grid')return `<section class="story-shelf"><div class="shelf-heading"><h2>Our story shelf</h2><span id="book-count">${it.books.filter(b=>st.storyCategory==='All'||b.category===st.storyCategory).length} stories</span></div><div class="book-grid">${it.books.map(b=>`<button class="book-tile" data-go="${booksById[b.id].detailId}" data-book="${b.id}" data-book-category="${esc(b.category)}" ${st.storyCategory!=='All'&&b.category!==st.storyCategory?'hidden':''} aria-label="Open ${esc(b.title)}"><span class="book-cover" data-cover="${b.id}">${booksById[b.id].cover}</span><span class="book-title">${esc(b.title)}</span></button>`).join('')}</div></section>`;
if(type==='book-intro'){const b=booksById[it.book.id];return `<div class="book-summary"><div class="book-cover book-detail-cover" data-cover="${b.id}">${b.cover}</div><h1 tabindex="-1">${esc(b.title)}</h1><div class="book-meta"><span>${esc(b.category)}</span><span>3 chapters</span></div><p class="book-description">${esc(b.description)}</p></div>`;}
if(type==='chapters')return `<section class="chapters-section"><h2 class="chapters-heading">Chapters</h2><div class="chapter-list">${it.book.chapters.map((c,n)=>`<button class="chapter-row" data-go="${it.routes[n]}"><span class="chapter-number">${String(n+1).padStart(2,'0')}</span><span class="chapter-name">${esc(c)}</span><span class="chev" aria-hidden="true">›</span></button>`).join('')}</div></section>`;
if(type==='chapter-art')return `<div class="art chapter-art" tabindex="0" role="button" aria-label="Zoom story illustration">${booksById[it.book.id].cover}</div>`;
'''
rep("if(type==='bento')return",branches+"if(type==='bento')return")
old='<header class="page-heading"><h1 tabindex="-1">${esc(s.title.replaceAll(\'Maya\',st.child))}</h1><p>${esc(s.sub.replaceAll(\'Maya\',st.child))}</p></header>'
rep(old,'${s.kind===\'book-detail\'?\'\':`'+old+'`}')
rep("if(b.dataset.theme){",'''if(b.dataset.category){st.storyCategory=b.dataset.category;const screen=b.closest('.screen');screen.querySelectorAll('[data-category]').forEach(c=>{const selected=c.dataset.category===st.storyCategory;c.setAttribute('aria-pressed',selected);c.textContent=(selected?'✓ ':'')+c.dataset.category});let count=0;screen.querySelectorAll('.book-tile').forEach(c=>{c.hidden=st.storyCategory!=='All'&&c.dataset.bookCategory!==st.storyCategory;if(!c.hidden){count++;animate(c,reduced()?[{opacity:0},{opacity:1}]:[{opacity:0,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:reduced()?120:240})}});screen.querySelector('#book-count').textContent=count+' stories';return}
if(b.dataset.theme){''')
rep("source?.classList.contains('card')&&s.kind==='detail'?source:null", "source?.classList.contains('book-tile')&&s.kind==='book-detail'?source.querySelector('.book-cover'):source?.classList.contains('card')&&s.kind==='detail'?source:null")
rep("next.querySelector('.art')?.getBoundingClientRect()","next.querySelector('.art,.book-detail-cover')?.getBoundingClientRect()")
rep("const ids=['reader','reader-2','reader-3']","const ids=byId[st.id].chapterRoutes||['reader','reader-2','reader-3']")
rep('window.LL={screens,st,go,render,theme};','window.LL={screens,books,st,go,render,theme};')
p.write_text(s,encoding='utf-8')
print('Stories layout and chapter navigation updated.')
