from html import escape

# Original sample stories for wireframe review, not a published catalogue.
BOOKS=[
 dict(id='seed',title='The little seed',category='Nature',description='A tiny seed discovers that growing takes patience, care, and its own special time.',chapters=['A quiet beginning','A little rain','Hello, little leaf'],copy=['A little seed rested in the soft earth. “When will I grow?” it wondered.','Rain tapped gently on the ground. The seed drank, rested, and reached one tiny root into the earth.','One morning, a green leaf reached toward the sun. The seed had been growing all along.'],colors=['#DDE7CB','#526B48','#F6F0D7'],motif='seed'),
 dict(id='kind',title='A kind little moment',category='Kindness',description='Milo learns that a small act of kindness can make someone’s whole day feel brighter.',chapters=['A lonely bench','Room for one more','Kindness comes around'],copy=['Milo saw someone sitting alone. He slowed down and gave a little wave.','“There is room beside me,” said Milo. Soon two quiet smiles became a happy conversation.','The next day, Milo felt shy. His new friend waved him over. A little kindness had found its way back.'],colors=['#F3DBD7','#AC675D','#FAEFE5'],motif='heart'),
 dict(id='cloud',title='The colour cloud',category='Feelings',description='A little cloud changes colour with every feeling and learns that all feelings are welcome.',chapters=['A blue morning','A rumble of red','All my colours'],copy=['The little cloud woke up blue. It told the sky, “I feel a little sad today.”','Later, a loud wind made the cloud feel red and cross. It paused for one slow breath, then another.','The cloud discovered it could feel many things. Every colour belonged in its sky.'],colors=['#DFDBF1','#75618E','#F8F1E0'],motif='cloud'),
 dict(id='brave',title='My brave little step',category='Adventure',description='Tara takes one small step toward something new, with a trusted hand beside her.',chapters=['Something new','One small step','Look what I tried'],copy=['The stepping stones looked a little far apart. Tara held her grown-up’s hand.','She tried the nearest stone first. Then she paused, looked, and tried the next one.','“I tried something new,” Tara said. Being brave could happen one little step at a time.'],colors=['#EAD8B8','#917044','#F7EEE0'],motif='path'),
 dict(id='shine',title='Together we shine',category='Kindness',description='Three little stars discover that helping one another makes the night a little brighter.',chapters=['Three little stars','A helping sparkle','Our bright night'],copy=['Three little stars wanted to light the path below. One was bright, one was small, and one was shy.','They moved closer and each shared a little sparkle. No one had to shine alone.','Together, they made a gentle light. There was a place for every star in their sky.'],colors=['#CCDCD9','#487C76','#FFF1C9'],motif='stars'),
 dict(id='moon',title='The moon’s goodnight',category='Bedtime',description='Follow the moon on a gentle journey as the world settles down for sleep.',chapters=['The evening hush','Goodnight, little world','Time to rest'],copy=['The moon peeked over the hill. All around, the busy day began to slow.','“Goodnight, trees. Goodnight, birds,” whispered the moon. The world grew softer and quieter.','One last window glowed. A little child closed their eyes, and the moon kept gentle watch.'],colors=['#D3D8EC','#596687','#FFF0C5'],motif='moon'),
 dict(id='giggle',title='Where did my giggle go?',category='Feelings',description='On a grumpy day, Nia learns to name her feelings and find comfort without rushing her smile.',chapters=['A grumpy morning','What do I need?','A little smile'],copy=['Nia could not find her giggle. Everything felt too loud and a little bit wrong.','“Maybe I need a cuddle and some quiet,” she said. Her grown-up listened and stayed close.','After a while, a funny little thought arrived. Nia smiled when she was ready.'],colors=['#F1E5BA','#AD873F','#FCF4DE'],motif='sun'),
 dict(id='puddle',title='Pip and the puddle',category='Adventure',description='A rainy-day walk becomes a little adventure full of noticing, wondering, and safe splashing.',chapters=['After the rain','A world in the water','One happy splash'],copy=['Pip put on boots and stepped outside with a grown-up. Rain had left little puddles along the path.','In one puddle, Pip spotted a cloud and a tree. The tiny pool was holding a piece of the sky.','With space around and a hand nearby, Pip made one happy splash. The rainy day had a new story.'],colors=['#CCE1E9','#4F7D92','#F1EBDA'],motif='puddle'),
 dict(id='wonders',title='A pocketful of wonders',category='Nature',description='A slow walk helps Sam notice the small treasures that make an ordinary day extraordinary.',chapters=['Let’s look closely','Tiny treasures','Wonders to remember'],copy=['Sam went for a slow walk. “What can we notice?” asked their grown-up.','A curled leaf, a smooth stone, and a bird’s little song became treasures to remember.','Sam left the living things where they belonged and carried the memories home.'],colors=['#DED4C6','#82705B','#F6EFDD'],motif='leaf'),
 dict(id='sleepy',title='The sleepy little fox',category='Bedtime',description='Fox follows a cosy evening routine and learns that resting is part of every adventure.',chapters=['One last adventure','Cosy little comforts','Dreams can wait'],copy=['Fox wanted one more adventure, but the stars were already coming out.','A wash, a warm cuddle, and a familiar story helped Fox feel cosy and safe.','“Tomorrow has room for more adventures,” whispered Fox, curling up for a restful night.'],colors=['#E8D1BF','#A26548','#FFF0DC'],motif='fox')
]

def detail_id(book):return 'story' if book['id']=='seed' else 'story-'+book['id']
def chapter_ids(book):return ['reader','reader-2','reader-3'] if book['id']=='seed' else ['reader-'+book['id']+'-'+str(i) for i in range(1,4)]

def cover_svg(book,gray=False):
    bg,ink,cream=book['colors'] if not gray else ['#E4E4DE','#62625E','#F7F7F3']
    motifs={
    'seed':f'<path d="M90 172V91" stroke="{ink}" stroke-width="4"/><path d="M90 135C58 134 46 112 52 94c27 1 39 18 38 41Zm0-20c0-27 17-46 43-42 0 26-16 43-43 42Z" fill="{ink}"/><ellipse cx="90" cy="175" rx="43" ry="10" fill="{ink}" opacity=".2"/>',
    'heart':f'<path d="M90 159s-53-32-53-61c0-27 37-32 53-5 16-27 53-22 53 5 0 29-53 61-53 61Z" fill="{ink}" opacity=".8"/><path d="M35 165h110" stroke="{ink}" stroke-width="2"/>',
    'cloud':f'<path d="M47 134c-25 0-25-39 0-41 6-33 57-39 73-9 34-3 47 50 9 50Z" fill="{cream}"/><path d="M58 150v13m31-11v23m31-25v12" stroke="{ink}" stroke-width="5" stroke-linecap="round"/>',
    'path':f'<path d="M22 180 67 106l28 42 31-66 43 98Z" fill="{ink}" opacity=".3"/><path d="M91 184c49-26-42-40-6-63" stroke="{cream}" stroke-width="10" fill="none"/><path d="M128 86V54l25 12-25 12" stroke="{ink}" stroke-width="3"/>',
    'stars':f'<path d="m90 67 10 29 31 2-24 19 7 30-24-18-25 18 8-30-25-19 31-2Z" fill="{cream}"/><path d="m37 132 5 12 13 2-10 8 2 13-10-7-11 7 3-13-10-8 13-2Zm106-57 4 10 11 2-8 7 2 11-9-6-9 6 3-11-9-7 11-2Z" fill="{ink}" opacity=".65"/>',
    'moon':f'<path d="M106 64c-32 34-13 78 28 81-47 26-89-6-82-43 4-22 26-37 54-38Z" fill="{cream}"/><circle cx="136" cy="74" r="3" fill="{ink}"/><circle cx="38" cy="153" r="3" fill="{ink}"/><path d="m134 112 4-8 4 8-4 8Z" fill="{cream}"/>',
    'sun':f'<circle cx="90" cy="119" r="39" fill="{cream}"/><path d="M76 127q14 18 28 0M90 59v-9M90 187v-9M30 119h-9M159 119h-9M47 76l-7-7m100 100-7-7M47 161l-7 7m100-99-7 7" stroke="{ink}" stroke-width="3" fill="none"/><circle cx="77" cy="112" r="3" fill="{ink}"/><circle cx="103" cy="112" r="3" fill="{ink}"/>',
    'puddle':f'<ellipse cx="90" cy="163" rx="60" ry="18" fill="{ink}" opacity=".25"/><path d="M51 97h29v49h17c16 0 18 20 0 20H51Zm52-12h28v51h15c15 0 15 17 0 17h-43Z" fill="{cream}"/><path d="M47 75v-9m54-9V45m43 34V67" stroke="{ink}" stroke-width="3" stroke-linecap="round"/>',
    'leaf':f'<path d="M53 165C27 87 81 66 139 76c9 61-25 96-86 89Z" fill="{ink}" opacity=".7"/><path d="m53 167 66-72m-38 41 2-31m16 13 24-1m-56 37-3-30" stroke="{cream}" stroke-width="2"/>',
    'fox':f'<path d="m47 86 37 16 34-26 28 69c-2 44-98 48-110 4Z" fill="{ink}"/><path d="m39 146 43-28 57 27c-17 34-78 38-100 1Z" fill="{cream}"/><path d="m61 143 8 3 8-4m24-3 8 4 8-4" stroke="{ink}" stroke-width="2" fill="none"/><path d="m81 154 8 6 8-7Z" fill="{ink}"/>'
    }
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="180" height="240" viewBox="0 0 180 240" role="img" aria-label="{escape(book["title"],quote=True)} cover"><rect width="180" height="240" rx="10" fill="{bg}"/><rect x="8" width="3" height="240" fill="{ink}" opacity=".13"/><circle cx="95" cy="117" r="68" fill="{cream}" opacity=".22"/><text x="94" y="28" text-anchor="middle" font-family="Arial,sans-serif" font-size="8" letter-spacing="2" fill="{ink}">LITTLE LEGACY</text>{motifs[book["motif"]]}<path d="M70 204h40" stroke="{ink}" stroke-width="1" opacity=".45"/><text x="93" y="223" text-anchor="middle" font-family="Arial,sans-serif" font-size="8" letter-spacing="1" fill="{ink}">{escape(book["category"].upper())}</text></svg>'
